Desapegando/src/Desapegando.Application/ViewModels/ProdutoViewModel.cs
using Desapegando.Business.Models.Enums;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Desapegando.Application.ViewModels
{
    public class ProdutoViewModel
    {
        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Nome")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Descrição")]
        public string Descricao { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Categoria")]
        public Categoria? Categoria { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Condição")]
        public EstadoProduto? EstadoProduto { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Preço")]
        public decimal? Preco { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Quantidade")]
        public int? Quantidade { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Imagens do Produto")]
        public List<IFormFile> ImagensUpload { get; set; }
    }

    public class UpdateProdutoViewModel
    {
        public Guid Id { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Nome")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Descrição")]
        public string Descricao { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Categoria")]
        public Categoria? Categoria { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Condição")]
        public EstadoProduto? EstadoProduto { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Preço")]
        public decimal? Preco { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Quantidade")]
        public int? Quantidade { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Imagens do Produto")]
        public List<IFormFile> ImagensUpload { get; set; }

        [DisplayName("Desistir da Venda")]
        public bool Desistencia { get; set; }

        [DisplayName("Disponível para Venda")]
        public bool Ativo { get; set; }

        [DisplayName("Produto Vendido")]
        public bool ProdutoVendido { get; set; }
    }

    public class GetProdutoViewModel
    {
        public Guid Id { get; set; }
        public string Nome { get; set; }

        public string Descricao { get; set; }

        public Categoria Categoria { get; set; }

        public EstadoProduto EstadoProduto { get; set; }

        public decimal Preco { get; set; }

        public int Quantidade { get; set; }
        public int Curtida { get; set; }

        public List<ProdutoImagemViewModel> ProdutoImagemViewModels { get; set; }
        public List<ProdutoCurtidaViewModel> ProdutoCurtidaViewModels { get; set; }
        public CondominoViewModel CondominoViewModel { get; set; }

        public bool Ativo { get; set; }
        public bool Desistencia { get; set; }
        public DateTime DataPublicacao { get; set; }
        public DateTime? DataDesistencia { get; set; }
    }

    public class FiltrarProdutoViewModel
    {
        public List<Categoria> Categorias { get; set; }
        public List<EnumModel> CheckBoxItems { get; set; }
        public decimal? PrecoMinimo { get; set; }
        public decimal? PrecoMaximo { get; set; }
    }

    public class EnumModel
    {
        public EstadoProduto EstadoProduto { get; set; }
        public bool IsSelected { get; set; }
    }

    public class PostProdutoViewModel
    {
        public Guid Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public Categoria? Categoria { get; set; }
        public EstadoProduto? EstadoProduto { get; set; }
        public decimal? Preco { get; set; }
        public int? Quantidade { get; set; }
        //public List<IFormFile> ImagensUpload { get; set; }
        public List<string> ImagensUploadNames { get; set; }
        public bool Desistencia { get; set; }
        //public bool Ativo { get; set; }
        public bool ProdutoVendido { get; set; }
        public DateTime DataPublicacao { get; set; }
        public DateTime? DataVenda { get; set; }
        public int Curtida { get; set; } = 0;
        public Guid CondominoId { get; set; }
    }

    public class PatchProdutoViewModel
    {
        public Guid Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public Categoria? Categoria { get; set; }
        public EstadoProduto? EstadoProduto { get; set; }
        public decimal? Preco { get; set; }
        public int? Quantidade { get; set; }
        //public List<IFormFile> ImagensUpload { get; set; }
        public List<string> ImagensUploadNames { get; set; }
        public bool Desistencia { get; set; }
        public bool Ativo { get; set; }
        public bool ProdutoVendido { get; set; }
        //public DateTime DataPublicacao { get; set; }
        public DateTime? DataVenda { get; set; }
        public int Curtida { get; set; } = 0;
        public Guid CondominoId { get; set; }
    }

    public class GetProdutoResponse
    {
        public bool Success { get; set; }
        public IEnumerable<ProdutoViewModel> Data { get; set; }
    }

    public class GetAllProdutoResponse
    {
        public bool Success { get; set; }
        public IEnumerable<GetProdutoViewModel> Data { get; set; }
    }

    public class GetProdutoResponseId
    {
        public bool Success { get; set; }
        //public ProdutoViewModel Data { get; set; }
        public GetProdutoViewModel Data { get; set; }
    }

    public class ProdutoResponse
    {
        public bool Success { get; set; }
        public DataProduto Data { get; set; }
    }
    
    public class DataProduto
    {
        public ResponseResult ResponseResult { get; set; }
    }

    public class GetMeusProdutoResponse
    {
        public bool Success { get; set; }
        public IEnumerable<GetProdutoViewModel> Data { get; set; }
    }

    public class CurtidaViewModel
    {
        public Guid ProdutoId { get; set; }
        public Guid CondominoId { get; set; }
    }
    public class DescurtidaViewModel
    {
        public Guid ProdutoId { get; set; }
        public Guid CondominoId { get; set; }
    }
    public class RemoverProdutoViewModel
    {
        public Guid ProdutoId { get; set; }
        public string Motivo { get; set; }
    }
}

Desapegando/src/Desapegando.Application/Controllers/ProdutoController.cs
using AutoMapper;
using Desapegando.Application.Services.MVC;
using Desapegando.Application.ViewModels;
using Desapegando.Business.Models;
using Desapegando.Business.Models.Enums;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace Desapegando.Application.Controllers;

public class ProdutoController : MainController
{
    private readonly IMapper _mapper;
    private readonly IProdutoService _produtoService;

    public ProdutoController(IProdutoService produtoService,
                             IMapper mapper)
    {
        _mapper = mapper;
        _produtoService = produtoService;
    }

    public async Task<IActionResult> Criar()
    {
        ProdutoViewModel model = new ProdutoViewModel();
        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Criar(ProdutoViewModel produtoViewModel)
    {
        if (!ModelState.IsValid)
        {
            return View(produtoViewModel);
        }

        if (produtoViewModel.ImagensUpload.Any() && produtoViewModel.ImagensUpload.Count > 4)
        {
            ModelState.AddModelError("ImagensUpload", "Só é possível adicionar no máximo 4 imagens.");
            return View(produtoViewModel);
        }

        var postProdutoViewModel = _mapper.Map<PostProdutoViewModel>(produtoViewModel);

        postProdutoViewModel.CondominoId = Guid.Parse(User.FindFirst("sub")?.Value);

        postProdutoViewModel.ImagensUploadNames = new List<string>();

        foreach (var imagem in produtoViewModel.ImagensUpload)
        {
            var imgPrefixo = Guid.NewGuid() + "_";
            if (!await UploadArquivo(imagem, imgPrefixo))
            {
                ModelState.AddModelError(string.Empty, "Ocorreu um erro ao salvar as imagens.");

                return View(produtoViewModel);
            }

            postProdutoViewModel.ImagensUploadNames.Add(imgPrefixo + imagem.FileName);
        }

        var response = await _produtoService.CriarProduto(postProdutoViewModel);

        if (ResponsePossuiErros(response))
        {
            ViewBag.Error = "Ocorreu um erro ao salvar";

            return View(produtoViewModel);
        }

        return RedirectToAction("Index", "Home");
    }

    public async Task<IActionResult> MeusProdutos()
    {
        var condominoId = Guid.Parse(User.FindFirst("sub")?.Value);

        var meusProdutos = await _produtoService.GetMeusProdutos(condominoId);

        return View(meusProdutos.Data);
    }

    public async Task<IActionResult> Editar(Guid id)
    {
        var response = await _produtoService.GetProduto(id);

        if (!response.Success)
        {
            ViewBag.Error = "Ocorreu um erro ao salvar";

            return View();
        }

        var produto = _mapper.Map<Produto>(response.Data);

        var updateProdutoViewModel = _mapper.Map<UpdateProdutoViewModel>(produto);

        return View(updateProdutoViewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Editar(UpdateProdutoViewModel produtoViewModel)
    {
        bool venda = false;
        int quantidadeVenda = 0;
        int quantidadeDb = 0;

        int quantidadeViewModel = produtoViewModel.Quantidade.Value;

        bool novasImagens = produtoViewModel.ImagensUpload != null;

        if (!novasImagens)
        {
            ModelState.ClearValidationState("ImagensUpload");
            ModelState.MarkFieldValid("ImagensUpload");
        }

        if (!ModelState.IsValid)
        {
            return View(produtoViewModel);
        }

        if (novasImagens && produtoViewModel.ImagensUpload.Count > 4)
        {
            ModelState.AddModelError("ImagensUpload", "Só é possível adicionar no máximo 4 imagens.");
            return View(produtoViewModel);
        }


        var patchProdutoViewModel = _mapper.Map<PatchProdutoViewModel>(produtoViewModel);

        patchProdutoViewModel.CondominoId = Guid.Parse(User.FindFirst("sub")?.Value);

        patchProdutoViewModel.ImagensUploadNames = new List<string>();

        var responseProduto = await _produtoService.GetProduto(produtoViewModel.Id);

        GetProdutoResponseId produtoDb = responseProduto;

        if (!produtoDb.Success)
        {
            return View(produtoViewModel);
        }

        //
        quantidadeDb = produtoDb.Data.Quantidade;

        if (produtoViewModel.Quantidade.Value == 0)
        {
            // não pode ter produto sem quantidade no banco de dados
            produtoDb.Data.Quantidade = 1;
            patchProdutoViewModel.Quantidade = 1;

            quantidadeViewModel = quantidadeDb;
        }

        if (!produtoViewModel.Ativo && !produtoViewModel.Desistencia)
        {
            quantidadeVenda = quantidadeDb - quantidadeViewModel;

            // nem todos os produtos (quantidade) foram vendidos
            if (quantidadeVenda != 0)
            {
                patchProdutoViewModel.Ativo = true;
                produtoDb.Data.Ativo = true;
            }

            //produtoDb.DataVenda = DateTime.Now;
            venda = true;

            if (quantidadeVenda == 0 && produtoViewModel.ProdutoVendido == true)
            {
                //patchProdutoViewModel.Ativo = false;
                //produtoDb.Data.Ativo = false;

                quantidadeVenda = quantidadeDb;

                // não pode ter produto sem quantidade no banco de dados
                patchProdutoViewModel.Quantidade = 1;
                produtoDb.Data.Quantidade = 1;
            }
        }

        //

        if (novasImagens)
        {
            foreach (var imagem in produtoViewModel.ImagensUpload)
            {
                var imgPrefixo = Guid.NewGuid() + "_";
                if (!await UploadArquivo(imagem, imgPrefixo))
                {
                    ModelState.AddModelError(string.Empty, "Ocorreu um erro ao salvar as imagens.");

                    return View(produtoViewModel);
                }

                patchProdutoViewModel.ImagensUploadNames.Add(imgPrefixo + imagem.FileName);
            }

            var listaProdutoImagensDb = produtoDb.Data.ProdutoImagemViewModels;
            // Deletando imagens antigas
            foreach (var imagem in listaProdutoImagensDb)
            {
                bool result = await DeletarArquivo(imagem.FileName);

                if (!result)
                {
                    ModelState.AddModelError(string.Empty, "Ocorreu um erro ao salvar as imagens.");
                }
            }
        }

        var response = await _produtoService.UpdateProduto(patchProdutoViewModel);

        if (ResponsePossuiErros(response))
        {
            ViewBag.Error = "Ocorreu um erro ao salvar";

            return View(produtoViewModel);
        }

        if (venda && quantidadeVenda >= 0)
        {
            if (quantidadeVenda == 0)
            {
                quantidadeVenda = quantidadeViewModel;
            }

            return RedirectToAction("Index", "Compra", new { produtoId = produtoViewModel.Id, quantidade = quantidadeVenda });
        }

        return RedirectToAction("Index", "Home");
    }

    public async Task<IActionResult> Visualizar(Guid id)
    {
        var response = await _produtoService.GetProduto(id);

        return View(response.Data);
    }

    public async Task<IActionResult> Produtos()
    {
        FiltrarProdutoViewModel model = new FiltrarProdutoViewModel();
        model.CheckBoxItems = new List<EnumModel>
        {
            new EnumModel() { EstadoProduto = EstadoProduto.Novo, IsSelected = false },
            new EnumModel() { EstadoProduto = EstadoProduto.Seminovo, IsSelected = false },
            new EnumModel() { EstadoProduto = EstadoProduto.Usado, IsSelected = false }
        };

        var response = await _produtoService.GetProdutos();

        var produtosDb = response.Data.Where(x => x.Ativo);

        if (!produtosDb.Any())
        {
            ViewBag.Produtos = Enumerable.Empty<GetProdutoViewModel>();

            return View(model);
        }

        ViewBag.Produtos = produtosDb;

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Produtos(FiltrarProdutoViewModel filtrarProdutoViewModel)
    {
        // por algum motivo não volta o valor do front end...
        filtrarProdutoViewModel.CheckBoxItems[0].EstadoProduto = EstadoProduto.Novo;
        filtrarProdutoViewModel.CheckBoxItems[1].EstadoProduto = EstadoProduto.Seminovo;
        filtrarProdutoViewModel.CheckBoxItems[2].EstadoProduto = EstadoProduto.Usado;

        if (filtrarProdutoViewModel.Categorias == null &&
            !filtrarProdutoViewModel.CheckBoxItems.Any(x => x.IsSelected) &&
            filtrarProdutoViewModel.PrecoMinimo == null &&
            filtrarProdutoViewModel.PrecoMaximo == null)
        {
            return RedirectToAction("Produtos");
        }

        var response = await _produtoService.GetProdutos();

        var produtosDb = response.Data.Where(x => (filtrarProdutoViewModel.Categorias != null && filtrarProdutoViewModel.Categorias.Contains(x.Categoria)) ||
                                                  ((filtrarProdutoViewModel.CheckBoxItems[0].EstadoProduto == x.EstadoProduto && filtrarProdutoViewModel.CheckBoxItems[0].IsSelected) ||
                                                  (filtrarProdutoViewModel.CheckBoxItems[1].EstadoProduto == x.EstadoProduto && filtrarProdutoViewModel.CheckBoxItems[1].IsSelected) ||
                                                  (filtrarProdutoViewModel.CheckBoxItems[2].EstadoProduto == x.EstadoProduto && filtrarProdutoViewModel.CheckBoxItems[2].IsSelected) ||
                                                  ((filtrarProdutoViewModel.PrecoMinimo != null && filtrarProdutoViewModel.PrecoMaximo != null) &&

Desapegando/src/Desapegando.Application/Views/Produto/Criar.cshtml
@using Desapegando.Business.Models.Enums;
@model Desapegando.Application.ViewModels.ProdutoViewModel
@{
    Layout = "_Layout";
}


<section class="pt-5 pb-9">
    <!-- ===============================================-->
    <!--    Main Content-->
    <!-- ===============================================-->
    <div class="container-small px-0">
        <div class="content">
            <form enctype="multipart/form-data" class="mb-9" method="post">
                <div class="row g-3 flex-between-end mb-5">
                    <div class="col-auto">
                        <h2 class="mb-2">Adicionar produto</h2>
                        <h5 class="text-700 fw-semi-bold">Adicione um produto para desapegar!</h5>
                    </div>
                    <div class="col-auto">
                        <button asp-action="Criar" asp-controller="Produto" class="btn btn-primary mb-2 mb-sm-0" type="submit">Salvar produto</button>
                    </div>
                </div>

                <vc:Summary></vc:Summary>

                <h4 class="mb-3">Nome do Produto</h4>
                <div class="row g-5">
                    <div class="col-12 col-xl-8">
                        <input asp-for="Nome" class="form-control mb-5" type="text" placeholder="Escreva o nome aqui..." />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                        <div class="mb-6">
                            <h4 class="mb-3">Descrição do Produto</h4>
                            <textarea asp-for="Descricao" type="text" class="tinymce" name="Descricao" data-tinymce='{"height":"15rem","placeholder":"Escreva a descrição aqui..."}'></textarea>
                            <span asp-validation-for="Descricao" class="text-danger"></span>
                        </div>
                        <div class="mb-6">
                            <h4 class="mb-3">Adicionar Imagens</h4>
                            <input class="form-control" type="file" name="ImagensUpload" multiple/>
                            <span asp-validation-for="ImagensUpload" class="text-danger"></span>
                        </div>

                        <h4 class="mb-3">Informações do Produto</h4>
                        <div class="row g-0 border-top border-bottom border-300">
                            <div class="col-sm-4">
                                <div class="nav flex-sm-column border-bottom border-bottom-sm-0 border-end-sm border-300 fs--1 vertical-tab h-100 justify-content-between" role="tablist" aria-orientation="vertical">
                                    <a class="nav-link border-end border-end-sm-0 border-bottom-sm border-300 text-center text-sm-start cursor-pointer outline-none d-sm-flex align-items-sm-center active" id="pricingTab" data-bs-toggle="tab" data-bs-target="#pricingTabContent" role="tab" aria-controls="pricingTabContent" aria-selected="true">
                                        <span class="me-sm-2 fs-4 nav-icons" data-feather="tag"></span>
                                        <span class="d-none d-sm-inline">Preço</span>
                                    </a>
                                    <a class="nav-link border-end border-end-sm-0 border-bottom-sm border-300 text-center text-sm-start cursor-pointer outline-none d-sm-flex align-items-sm-center" id="restockTab" data-bs-toggle="tab" data-bs-target="#restockTabContent" role="tab" aria-controls="restockTabContent" aria-selected="false">
                                        <span class="me-sm-2 fs-4 nav-icons" data-feather="package"></span>
                                        <span class="d-none d-sm-inline">Quantidade</span>
                                    </a>
                                </div>
                            </div>
                            <div class="col-sm-8">
                                <div class="tab-content py-3 ps-sm-4 h-100">
                                    <div class="tab-pane fade show active" id="pricingTabContent" role="tabpanel">
                                        <h4 class="mb-3 d-sm-none">Pricing</h4>
                                        <div class="row g-3">
                                            <div class="col-12 col-lg-6">
                                                <h5 class="mb-2 text-1000">Preço</h5>
                                                <input asp-for="Preco" class="form-control" type="text" placeholder="$$$" />
                                                <span asp-validation-for="Preco" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane fade h-100" id="restockTabContent" role="tabpanel" aria-labelledby="restockTab">
                                        <div class="d-flex flex-column h-100">
                                            <h5 class="mb-3 text-1000">Quantidade</h5>
                                            <div class="row g-3 flex-1 mb-4">
                                                <div class="col-sm-7">
                                                    <input asp-for="Quantidade" class="form-control" type="number" placeholder="Quantidade" />
                                                    <span asp-validation-for="Quantidade" class="text-danger"></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-xl-4">
                        <div class="row g-2">
                            <div class="col-12 col-xl-12">
                                <div class="card mb-3">
                                    <div class="card-body">
                                        <h4 class="card-title mb-4">Organização</h4>
                                        <div class="row g-3">
                                            <div class="col-12 col-sm-6 col-xl-12">
                                                <div class="mb-4">
                                                    <div class="d-flex flex-wrap mb-2">
                                                        <h5 class="mb-0 text-1000 me-2">Categoria</h5>
                                                    </div>
                                                    <select asp-for="Categoria" class="form-select" asp-items="@Html.GetEnumSelectList<Categoria>()">
                                                        <option selected="" value="">Selecione</option>
                                                    </select>
                                                    <span asp-validation-for="Categoria" class="text-danger"></span>
                                                </div>
                                            </div>
                                            <div class="col-12 col-sm-6 col-xl-12">
                                                <div class="mb-4">
                                                    <div class="d-flex flex-wrap mb-2">
                                                        <h5 class="mb-0 text-1000 me-2">Estado do Produto</h5>
                                                    </div>
                                                    <select asp-for="EstadoProduto" class="form-select" asp-items="@Html.GetEnumSelectList<EstadoProduto>()">
                                                        <option selected="" value="">Selecione</option>
                                                    </select>
                                                    <span asp-validation-for="EstadoProduto" class="text-danger"></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- ===============================================-->
    <!--    End of Main Content-->
    <!-- ===============================================-->
</section>

@section Scripts{
    <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link href="~/public/vendors/dropzone/dropzone.min.css" rel="stylesheet">
    <link href="~/public/vendors/choices/choices.min.css" rel="stylesheet">
    <link href="~/public/vendors/flatpickr/flatpickr.min.css" rel="stylesheet">
    <link href="~/public/assets/css/theme.min.css" type="text/css" rel="stylesheet" id="style-default">


    <!-- ===============================================-->
    <!--    JavaScripts-->
    <!-- ===============================================-->
    <script src="~/public/vendors/tinymce/tinymce.min.js"></script>
    <script src="~/public/vendors/dropzone/dropzone.min.js"></script>
    <script src="~/public/vendors/choices/choices.min.js"></script>
}