Desapegando/src/Desapegando.Application/ViewModels/CampanhaViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Desapegando.Application.ViewModels
{
    public class CampanhaViewModel
    {
        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Nome")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Nome Instituição")]
        public string NomeInstituicao { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Descrição")]
        public string Descricao { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Nome do Responsável")]
        public string NomeResponsavel { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [EmailAddress(ErrorMessage = "O campo {0} está em formato inválido")]
        [DisplayName("E-mail do Responsável")]
        public string EmailResponsavel { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Telefone do Responsável")]
        public string TelefoneResponsavel { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Local de Encontro")]
        public string LocalDeEncontro { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [DisplayName("Data de Início")]
        public DateTime? DataInicio { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [DisplayName("Data Final")]
        public DateTime? DataFinal { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Imagens do Produto")]
        public List<IFormFile> ImagensUpload { get; set; }
    }

    public class UpdateCampanhaViewModel
    {
        public Guid Id { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Nome")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Nome Instituição")]
        public string NomeInstituicao { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Descrição")]
        public string Descricao { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Nome do Responsável")]
        public string NomeResponsavel { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [EmailAddress(ErrorMessage = "O campo {0} está em formato inválido")]
        [DisplayName("E-mail do Responsável")]
        public string EmailResponsavel { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Telefone do Responsável")]
        public string TelefoneResponsavel { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Local de Encontro")]
        public string LocalDeEncontro { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [DisplayName("Data de Início")]
        public DateTime? DataInicio { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [DisplayName("Data Final")]
        public DateTime? DataFinal { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Imagens do Produto")]
        public List<IFormFile> ImagensUpload { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Campanha Ativa")]
        public bool Ativo { get; set; }
    }

    public class GetCampanhaViewModel
    {
        public Guid Id { get; set; }
        public string Nome { get; set; }
        public string NomeInstituicao { get; set; }
        public string Descricao { get; set; }
        public string NomeResponsavel { get; set; }
        public string EmailResponsavel { get; set; }
        public string TelefoneResponsavel { get; set; }
        public string LocalDeEncontro { get; set; }
        public DateTime DataInicio { get; set; }
        public DateTime DataFinal { get; set; }
        public List<IFormFile> ImagensUpload { get; set; }
        public bool Ativo { get; set; }
        public List<CampanhaImagemViewModel> CampanhaImagemViewModels { get; set; }
    }

    public class FiltrarCampanhaViewModel
    {
        public string Nome { get; set; }
        public string NomeInstituicao { get; set; }
    }

    public class PostCampanhaViewModel
    {
        public Guid Id { get; set; }
        public string Nome { get; set; }
        public string NomeInstituicao { get; set; }
        public string Descricao { get; set; }
        public string NomeResponsavel { get; set; }
        public string EmailResponsavel { get; set; }
        public string TelefoneResponsavel { get; set; }
        public string LocalDeEncontro { get; set; }
        public DateTime DataInicio { get; set; }
        public DateTime DataFinal { get; set; }
        public List<string> ImagensUploadNames { get; set; }
        //public bool Ativo { get; set; }
        public Guid CondominoId { get; set; }
    }

    public class GetCampanhaResponse
    {
        public bool Success { get; set; }
        public IEnumerable<CampanhaViewModel> Data { get; set; }
    }

    public class GetAllCampanhaResponse
    {
        public bool Success { get; set; }
        public IEnumerable<GetCampanhaViewModel> Data { get; set; }
    }

    public class GetCampanhaResponseId
    {
        public bool Success { get; set; }
        //public CampanhaViewModel Data { get; set; }
        public GetCampanhaViewModel Data { get; set; }
    }

    public class CampanhaResponse
    {
        public bool Success { get; set; }
        public DataCampanha Data { get; set; }
    }

    public class DataCampanha
    {
        public ResponseResult ResponseResult { get; set; }
    }

    public class GetMinhasCampanhasResponse
    {
        public bool Success { get; set; }
        public IEnumerable<GetCampanhaViewModel> Data { get; set; }
    }

    public class PatchCampanhaViewModel
    {
        public Guid Id { get; set; }
        public string Nome { get; set; }
        public string NomeInstituicao { get; set; }
        public string Descricao { get; set; }
        public string NomeResponsavel { get; set; }
        public string EmailResponsavel { get; set; }
        public string TelefoneResponsavel { get; set; }
        public string LocalDeEncontro { get; set; }
        public DateTime? DataInicio { get; set; }
        public DateTime? DataFinal { get; set; }
        public List<string> ImagensUploadNames { get; set; }
        public bool Ativo { get; set; }
        public Guid CondominoId { get; set; }
    }
}

Desapegando/src/Desapegando.Application/Controllers/CampanhaController.cs
using AutoMapper;
using Desapegando.Application.Extensions;
using Desapegando.Application.Services.MVC;
using Desapegando.Application.ViewModels;
using Desapegando.Business.Interfaces.Notifications;
using Desapegando.Business.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Text;
using System.Text.Json;

namespace Desapegando.Application.Controllers;

public class CampanhaController : MainController
{
    private readonly IMapper _mapper;
    private readonly ICampanhaService _campanhaService;

    public CampanhaController(ICampanhaService campanhaService,
                              IMapper mapper)
    {
        _mapper = mapper;
        _campanhaService = campanhaService;
    }

    public async Task<IActionResult> Criar()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Criar(CampanhaViewModel campanhaViewModel)
    {
        if (!ModelState.IsValid)
        {
            return View(campanhaViewModel);
        }

        if (campanhaViewModel.ImagensUpload.Any() && campanhaViewModel.ImagensUpload.Count > 4)
        {
            ModelState.AddModelError("ImagensUpload", "Só é possível adicionar no máximo 4 imagens.");
            return View(campanhaViewModel);
        }

        var postCampanhaViewModel = _mapper.Map<PostCampanhaViewModel>(campanhaViewModel);

        postCampanhaViewModel.CondominoId = Guid.Parse(User.FindFirst("sub")?.Value);

        postCampanhaViewModel.ImagensUploadNames = new List<string>();

        foreach (var imagem in campanhaViewModel.ImagensUpload)
        {
            var imgPrefixo = Guid.NewGuid() + "_";
            if (!await UploadArquivo(imagem, imgPrefixo))
            {
                ModelState.AddModelError(string.Empty, "Ocorreu um erro ao salvar as imagens.");

                return View(campanhaViewModel);
            }

            postCampanhaViewModel.ImagensUploadNames.Add(imgPrefixo + imagem.FileName);
        }

        var response = await _campanhaService.CriarCampanha(postCampanhaViewModel);

        if (ResponsePossuiErros(response))
        {
            ViewBag.Error = "Ocorreu um erro ao salvar";

            return View(campanhaViewModel);
        }

        return RedirectToAction("Index", "Home");
    }

    public async Task<IActionResult> MinhasCampanhas()
    {
        var condominoId = Guid.Parse(User.FindFirst("sub")?.Value);

        var response = await _campanhaService.GetMinhasCampanhas(condominoId);

        return View(response.Data);
    }

    public async Task<IActionResult> Editar(Guid id)
    {
        var response = await _campanhaService.GetCampanha(id);

        if (!response.Success)
        {
            ViewBag.Error = "Ocorreu um erro ao salvar";

            return View();
        }

        var campanha = _mapper.Map<Campanha>(response.Data);

        var updateCampanhaViewModel = _mapper.Map<UpdateCampanhaViewModel>(campanha);

        return View(updateCampanhaViewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Editar(UpdateCampanhaViewModel campanhaViewModel)
    {
        bool novasImagens = campanhaViewModel.ImagensUpload != null;

        if (!novasImagens)
        {
            ModelState.ClearValidationState("ImagensUpload");
            ModelState.MarkFieldValid("ImagensUpload");
        }

        if (!ModelState.IsValid)
        {
            return View(campanhaViewModel);
        }

        if (novasImagens && campanhaViewModel.ImagensUpload.Count > 4)
        {
            ModelState.AddModelError("ImagensUpload", "Só é possível adicionar no máximo 4 imagens.");
            return View(campanhaViewModel);
        }

        var patchCampanhaViewModel = _mapper.Map<PatchCampanhaViewModel>(campanhaViewModel);

        patchCampanhaViewModel.CondominoId = Guid.Parse(User.FindFirst("sub")?.Value);

        patchCampanhaViewModel.ImagensUploadNames = new List<string>();

        if (novasImagens)
        {
            foreach (var imagem in campanhaViewModel.ImagensUpload)
            {
                var imgPrefixo = Guid.NewGuid() + "_";
                if (!await UploadArquivo(imagem, imgPrefixo))
                {
                    ModelState.AddModelError(string.Empty, "Ocorreu um erro ao salvar as imagens.");

                    return View(campanhaViewModel);
                }

                patchCampanhaViewModel.ImagensUploadNames.Add(imgPrefixo + imagem.FileName);
            }

            var responseCampanha = await _campanhaService.GetCampanha(campanhaViewModel.Id);

            GetCampanhaResponseId campanhaDb;

            campanhaDb = responseCampanha;


            if (!campanhaDb.Success)
            {
                return View(campanhaViewModel);
            }

            var listaProdutoImagensDb = campanhaDb.Data.CampanhaImagemViewModels;
            // Deletando imagens antigas
            foreach (var imagem in listaProdutoImagensDb)
            {
                bool result = await DeletarArquivo(imagem.FileName);

                if (!result)
                {
                    ModelState.AddModelError(string.Empty, "Ocorreu um erro ao salvar as imagens.");
                }
            }
        }

        var response = await _campanhaService.UpdateCampanha(patchCampanhaViewModel);

        if (ResponsePossuiErros(response))
        {
            ViewBag.Error = "Ocorreu um erro ao salvar";

            return View(campanhaViewModel);
        }

        return RedirectToAction("Index", "Home");
    }

    public async Task<IActionResult> Visualizar(Guid id)
    {
        var response = await _campanhaService.GetCampanha(id);

        return View(response.Data);
    }

    public async Task<IActionResult> Deletar(Guid id)
    {
        var response = await _campanhaService.DeletarCampanha(id);

        if (ResponsePossuiErros(response))
        {
            return View();
        }

        return RedirectToAction("MinhasCampanhas");
    }

    public async Task<IActionResult> Campanhas()
    {
        var response = await _campanhaService.GetCampanhas();

        var campanhasDb = response.Data.Where(x => x.Ativo);

        if (!campanhasDb.Any())
        {
            ViewBag.Campanhas = Enumerable.Empty<GetCampanhaViewModel>();
            
            return View();
        }

        ViewBag.Campanhas = campanhasDb;

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Campanhas(FiltrarCampanhaViewModel filtrarCampanhaViewModel)
    {
        if (string.IsNullOrEmpty(filtrarCampanhaViewModel.Nome) && string.IsNullOrEmpty(filtrarCampanhaViewModel.NomeInstituicao))
        {
            return RedirectToAction("Campanhas");
        }

        var response = await _campanhaService.GetCampanhas();

        var campanhasDb = response.Data.Where(x => ((!string.IsNullOrEmpty(filtrarCampanhaViewModel.Nome) && x.Nome.ToLower().Trim().Contains(filtrarCampanhaViewModel.Nome.ToLower().Trim())) ||
                                                   (!string.IsNullOrEmpty(filtrarCampanhaViewModel.NomeInstituicao) && x.NomeInstituicao.ToLower().Trim().Contains(filtrarCampanhaViewModel.NomeInstituicao.ToLower().Trim())))
                                                   && x.Ativo == true);

        if (!campanhasDb.Any())
        {
            ViewBag.Campanhas = Enumerable.Empty<GetCampanhaViewModel>();
            
            return View();
        }

        var campanhasViewModel = _mapper.Map<IEnumerable<GetCampanhaViewModel>>(campanhasDb);

        ViewBag.Campanhas = campanhasViewModel;

        return View();
    }

    #region MétodosPrivados
    private async Task<bool> UploadArquivo(IFormFile arquivo, string imgPrefixo)
    {
        if (arquivo.Length <= 0) return false;

        var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Imagens", imgPrefixo + arquivo.FileName);

        //verificar se o arquivo já existe no diretório
        if (System.IO.File.Exists(path))
        {
            ModelState.AddModelError(string.Empty, "Já existe um arquivo com este nome!");
            return false;
        }


        // gravando em "disco"
        using (var stream = new FileStream(path, FileMode.Create))
        {
            await arquivo.CopyToAsync(stream);
        }

        return true;
    }

    private async Task<bool> DeletarArquivo(string imagem)
    {
        if (imagem.Length <= 0) return false;

        var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/imagens", imagem);

        //verificar se o arquivo já existe no diretório
        if (System.IO.File.Exists(path))
        {
            System.IO.File.Delete(path);
            return true;
        }

        return false;
    }

    private static void MapearCampanha(Campanha campanha, UpdateCampanhaViewModel campanhaViewModel)
    {
        campanha.Nome = campanhaViewModel.Nome;
        campanha.Descricao = campanhaViewModel.Descricao;
        campanha.Ativo = campanhaViewModel.Ativo;
        campanha.NomeInstituicao = campanhaViewModel.NomeInstituicao;
        campanha.DataInicio = campanhaViewModel.DataInicio.Value;
        campanha.DataFinal = campanhaViewModel.DataFinal.Value;
        campanha.EmailResponsavel = campanhaViewModel.EmailResponsavel;
        campanha.LocalDeEncontro = campanhaViewModel.LocalDeEncontro;
        campanha.NomeResponsavel = campanhaViewModel.NomeResponsavel;
        campanha.TelefoneResponsavel = campanhaViewModel.TelefoneResponsavel;
    }
    #endregion
}


Desapegando/src/Desapegando.Application/Views/Campanha/Campanhas.cshtml
@using Desapegando.Business.Models.Enums;
@model Desapegando.Application.ViewModels.FiltrarCampanhaViewModel

@{
    var listaCampanhas = ViewBag.Campanhas;
}
@{
    Layout = "_Layout";
}

<section class="pt-5 pb-9">
    <div class="container">
        <button class="btn btn-sm btn-phoenix-secondary text-700 mb-5 d-lg-none" data-phoenix-toggle="offcanvas" data-phoenix-target="#productFilterColumn"> <span class="fa-solid fa-filter me-2"></span>Filtro</button>
        <div class="row">
            <div class="col-lg-3 col-xxl-2 ps-2">
                <div class="product-filter-offcanvas bg-soft scrollbar phoenix-offcanvas phoenix-offcanvas-fixed" id="productFilterColumn">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h3 class="mb-0 ms-1">Filtros</h3>
                        <button class="btn d-lg-none p-0" data-phoenix-dismiss="offcanvas"><span class="uil uil-times fs-0"></span></button>
                    </div><a class="btn px-0 ms-1 d-block collapse-indicator" data-bs-toggle="collapse" href="#collapseAvailability" role="button" aria-expanded="true" aria-controls="collapseAvailability">
                        <div class="d-flex align-items-center justify-content-between w-100">
                            <div class="fs-0 text-1000">Nome</div><span class="fa-solid fa-angle-down toggle-icon text-500"></span>
                        </div>
                    </a>
                    <form method="post">
                        <div class="collapse ms-1 show" id="collapseAvailability">
                            <div class="mb-2">
                                <div class="form mb-0 p-0">
                                    <div class="mb-2">
                                        <div class="mb-3 text-start">
                                            <input asp-for="Nome" class="form-control" placeholder="Nome" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a class="btn px-0 ms-1 d-block collapse-indicator" data-bs-toggle="collapse" href="#collapseCondition" role="button" aria-expanded="true" aria-controls="collapseCondition">
                            <div class="d-flex align-items-center justify-content-between w-100">
                                <div class="fs-0 text-1000">Nome da Instituição</div><span class="fa-solid fa-angle-down toggle-icon text-500"></span>
                            </div>
                        </a>
                        <div class="collapse ms-1 show" id="collapseCondition">
                            <div class="mb-2">
                                <div class="form mb-0 p-0">
                                    <div class="mb-2">
                                        <div class="mb-3 text-start">
                                            <input asp-for="NomeInstituicao" class="form-control" placeholder="Nome da Instituição" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button asp-action="Campanhas" asp-controller="Campanha" class="btn btn-phoenix-primary border-300 px-3" type="submit">Pesquisar</button>
                    </form>
                </div>
                <div class="phoenix-offcanvas-backdrop d-lg-none" data-phoenix-backdrop></div>
            </div>
            <div class="col-lg-9 col-xxl-10">
                <div class="row gx-3 gy-6 mb-8">
                    @foreach (var campanha in listaCampanhas)
                    {
                        <div class="col-12 col-sm-6 col-md-4 col-xxl-2">
                            <div class="product-card-container h-100">
                                <div class="position-relative text-decoration-none product-card h-100">
                                    <div class="d-flex flex-column justify-content-between h-100">
                                        <div>
                                            <div class="border border-1 rounded-3 position-relative mb-3">
                                                @*  <button class="btn rounded-circle p-0 d-flex flex-center btn-wish z-index-2 d-toggle-container btn-outline-primary" data-bs-toggle="tooltip" data-bs-placement="top" title="Add to wishlist">
                                            <span class="fas fa-heart d-block-hover"></span><span class="far fa-heart d-none-hover"></span>
                                            </button><img class="img-fluid" src="~/Imagens/@campanha.CampanhaImagemViewModels[0].FileName" alt="" />*@
                                                <img src="~/Imagens/@campanha.CampanhaImagemViewModels[0].FileName" alt="" height="212.38px" width="212.38px" />
                                            </div><a class="stretched-link text-decoration-none" asp-action="Visualizar" asp-controller="Campanha" asp-route-id="@campanha.Id">
                                                <h6 class="mb-2 lh-sm line-clamp-3 product-name">@campanha.Nome</h6>
                                            </a>
                                            <p class="fs--1">
                                                <span class="text-500 fw-semi-bold ms-1">Local de Encontro: @campanha.LocalDeEncontro</span>
                                            </p>
                                        </div>
                                        <div>
                                            <p class="text-700 fw-semi-bold fs--1 lh-1 mb-0">Instituição: @campanha.NomeInstituicao</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <div class="d-flex justify-content-end">
                    <button class="page-link" data-list-pagination="prev"><span class="fas fa-chevron-left"></span></button>
                    <ul class="mb-0 pagination"></ul>
                    <button class="page-link pe-0" data-list-pagination="next"><span class="fas fa-chevron-right"></span></button>

                </div>
            </div>
        </div>
    </div>

    <!-- end of .container-->

</section>

@section Scripts{
    <link href="~/public/vendors/choices/choices.min.css" rel="stylesheet" />
    <script src="~/public/vendors/choices/choices.min.js"></script>
}

Desapegando/src/Desapegando.Application/Views/Campanha/MinhasCampanhas.cshtml
@using Desapegando.Business.Models.Enums;
@model IEnumerable<Desapegando.Application.ViewModels.GetCampanhaViewModel>
@*@{
    Layout = "_Layout";
}*@






    <!-- ===============================================-->
    <!--    Main Content-->
    <!-- ===============================================-->
    <main class="main" id="top">
        <!-- ============================================-->
        <!-- <section> begin ============================-->
        <section class="pt-5 pb-9">

            <div class="container-small cart">
                <h2 class="mb-5">Minhas Campanhas<span class="text-700 fw-normal ms-2">(@Model.Count())</span></h2>
                <div class="border-y" id="productWishlistTable" data-list='{"valueNames":["products","color","size","price","quantity","total"],"page":5,"pagination":true}'>
                    <div class="table-responsive scrollbar">
                        <table class="table fs--1 mb-0">
                            <thead>
                                <tr>
                                    <th class="sort white-space-nowrap align-middle fs--2" scope="col" style="width:7%;"></th>
                                    <th class="sort white-space-nowrap align-middle" scope="col" style="width:30%; min-width:250px;" data-sort="products">CAMPANHAS</th>
                                    <th class="sort align-middle" scope="col" data-sort="color" style="width:16%;">NOME</th>
                                    <th class="sort align-middle" scope="col" data-sort="size" style="width:10%;">NOME INSTITUIÇÃO</th>
                                    <th class="sort align-middle text-end" scope="col" data-sort="price" style="width:10%;">LOCAL DE ENCONTRO</th>
                                    <th class="sort align-middle text-end pe-0" scope="col" style="width:35%;"> </th>
                                </tr>
                            </thead>
                            <tbody class="list" id="profile-wishlist-table-body">

                                @foreach (var campanha in Model)
                            {
                                <tr class="hover-actions-trigger btn-reveal-trigger position-static">
                                    <td class="align-middle white-space-nowrap ps-0 py-0">
                                        <div class="border rounded-2 d-inline-block"><img src="~/Imagens/@campanha.CampanhaImagemViewModels[0].FileName" alt="" width="53" /></div>
                                    </td>
                                    <td class="products align-middle pe-11"><a class="fw-semi-bold mb-0 line-clamp-1" asp-action="Visualizar" asp-controller="Campanha" asp-route-id="@campanha.Id">@campanha.Nome</a></td>
                                    <td class="color align-middle white-space-nowrap fs--1 text-900">@campanha.Nome</td>
                                    <td class="size align-middle white-space-nowrap text-700 fs--1 fw-semi-bold">@campanha.NomeInstituicao</td>
                                    <td class="price align-middle text-900 fs--1 fw-semi-bold text-end">@campanha.LocalDeEncontro</td>
                                    <td class="total align-middle fw-bold text-1000 text-end text-nowrap pe-0">
                                        <a class="btn btn-sm text-500 hover-text-600 me-2" asp-action="Deletar" asp-controller="Campanha" asp-route-id="@campanha.Id"><span class="fas fa-trash"></span></a>
                                        <a class="btn btn-primary fs--2" asp-action="Editar" asp-controller="Campanha" asp-route-id="@campanha.Id"><span class="fas fa-shopping-cart me-1 fs--2"></span>Editar</a>
                                    </td>
                                </tr>
                            }

                            </tbody>
                        </table>
                    </div>
                    <div class="row align-items-center justify-content-between py-2 pe-0 fs--1">
                        <div class="col-auto d-flex">
                            <p class="mb-0 d-none d-sm-block me-3 fw-semi-bold text-900" data-list-info="data-list-info"></p><a class="fw-semi-bold" href="#!" data-list-view="*">View all<span class="fas fa-angle-right ms-1" data-fa-transform="down-1"></span></a><a class="fw-semi-bold d-none" href="#!" data-list-view="less">View Less<span class="fas fa-angle-right ms-1" data-fa-transform="down-1"></span></a>
                        </div>
                        <div class="col-auto d-flex">
                            <button class="page-link" data-list-pagination="prev"><span class="fas fa-chevron-left"></span></button>
                            <ul class="mb-0 pagination"></ul>
                            <button class="page-link pe-0" data-list-pagination="next"><span class="fas fa-chevron-right"></span></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end of .container-->

        </section>
        <!-- <section> close ============================-->
        <!-- ============================================-->


    </main>
    <!-- ===============================================-->
    <!--    End of Main Content-->
    <!-- ===============================================-->